
import React, { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { QrCode, Link, Star } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

const MagicalQRSection = () => {
  const [qrGenerated, setQrGenerated] = useState(false);
  const { toast } = useToast();
  
  // Mock magical link - in real app this would be generated by backend
  const magicalLink = "https://reviews.magical.link/abc123";

  const handleGenerateQR = () => {
    setQrGenerated(true);
    toast({
      title: "QR Code Generated!",
      description: "Your magical QR code is ready to share with customers.",
    });
  };

  const handleCopyLink = () => {
    navigator.clipboard.writeText(magicalLink);
    toast({
      title: "Link Copied!",
      description: "Magical review link copied to clipboard.",
    });
  };

  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="flex items-center gap-2 text-lg">
          ✨ Magical QR & Link
        </CardTitle>
        <p className="text-sm text-gray-600">
          Share this special link - 5⭐ reviews go to Google, others come to your dashboard
        </p>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="bg-gradient-to-r from-purple-50 to-blue-50 p-4 rounded-lg border">
          <div className="flex items-center gap-2 mb-2">
            <Star className="h-4 w-4 text-yellow-500" fill="currentColor" />
            <span className="text-sm font-medium">How it works:</span>
          </div>
          <p className="text-xs text-gray-600">
            5-star reviews → Google Business Profile<br/>
            1-4 star reviews → Your private dashboard
          </p>
        </div>

        <div className="space-y-3">
          <div>
            <label className="text-sm font-medium text-gray-700 block mb-2">
              Your Magical Link:
            </label>
            <div className="flex gap-2">
              <div className="flex-1 p-2 bg-gray-50 border rounded text-sm font-mono text-gray-700">
                {magicalLink}
              </div>
              <Button 
                size="sm" 
                variant="outline" 
                onClick={handleCopyLink}
                className="flex items-center gap-1"
              >
                <Link className="h-3 w-3" />
                Copy
              </Button>
            </div>
          </div>

          <div className="flex gap-2">
            <Button 
              size="sm" 
              onClick={handleGenerateQR}
              className="flex items-center gap-1"
              disabled={qrGenerated}
            >
              <QrCode className="h-3 w-3" />
              {qrGenerated ? "QR Generated ✓" : "Generate QR Code"}
            </Button>
            <Button size="sm" variant="outline">
              Download QR
            </Button>
            <Button size="sm" variant="outline">
              Print QR
            </Button>
          </div>
        </div>

        <div className="pt-3 border-t">
          <div className="flex items-center justify-between text-sm">
            <span className="text-gray-600">This month:</span>
            <div className="flex gap-4">
              <span className="text-green-600 font-medium">12 to Google ⭐</span>
              <span className="text-blue-600 font-medium">3 to Dashboard 📝</span>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default MagicalQRSection;
